config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'topics/new'
  get 'sessions/new'
  get 'users/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#index'
  get 'pages/help'
  get 'pages/schedule'
  get 'pages/about'

  resources :users

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users
  resources :topics
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates :user_id, presence: true
  validates :description, presence: true
  validates :image, presence: true

  belongs_to :user

  mount_uploader :image, ImageUploader

end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: (1..40)
  validates :email, presence: true, format: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  has_secure_password
    validates :password, length: (8..32), presence: true, format: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i

  has_many :topics
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  add_flash_types :success, :info, :warning, :danger

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
    @current_user = User.find(params[:id])
  end

  def logged_in?
    !current_user.nil?
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def help
  end

  def schedule
  end

  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email_params)
    if user && user.authenticate(password_params[:password])
      log_in user
      redirect_to pages_schedule_path, success: 'Logged In!'
    else
      flash.now[:danger] = 'Try again'
      render :new
    end
  end

  def destroy
    log_out
    redirect_to root_url, info: 'Logged Out!'
  end

  private
  def log_in(user)
    session[:user_id] = user.id
  end

  def email_params
    params.require(:session).permit(:email)
  end

  def password_params
    params.require(:session).permit(:password)
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.all
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = current_user.topics.new(topic_params)
    if @topic.save
      redirect_to topics_path, success: 'Posted'
    else
      flash.now[:danger] = "Try again"
      render :new
    end
  end

  private
  def topic_params
    params.require(:topic).permit(:image, :description)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, success: 'REGISTERED!'
    else
      flash.now[:danger] = "REGISTRATION FAILED"
      render :new
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ABC</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab" rel="stylesheet">
  </head>

  <body>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>" role="alert"><%= value %></div>
    <% end %>

    <nav class="navbar navbar-default navbar-fixed-top navbar-transparent">
      <div class="container">
        <% if logged_in? %>
          <%= link_to pages_schedule_path do %>
          <%= image_tag "icons/logo.png", class: 'top-logo' %>
        <% end %>
          <a class="login-user">User:  Hi! <%= current_user.name %>!</a>
      <% else %>
        <%= link_to root_path do %>
        <%= image_tag "icons/logo.png", class: 'top-logo' %>
      <% end %>
      <a class="login-user">Please Login.</a>
    <% end %>
    <ul class="nav navbar-nav navbar-right">
      <% if logged_in? %>
        <li>
          <%= link_to pages_schedule_path do %>
          <%= image_tag "icons/calendar.png" %>
        <% end %>
      </li>
      <li>
        <%= link_to topics_path do %>
        <%= image_tag "icons/camera.png" %>
      <% end %>
    </li>
    <li>
      <%= link_to pages_about_path do %>
      <%= image_tag "icons/about.png" %>
      <% end %>
    </li>
    <li>
      <%= link_to logout_path, method: :delete do %>
      <%= image_tag "icons/logout.png" %>
    <% end %>
  </li>

<% else %>
<li>
  <%= link_to new_user_path do %>
  <%= image_tag "icons/register.png" %>
<% end %>
</li>
<li>
<%= link_to login_path do %>
<%= image_tag "icons/login.png" %>
<% end %>
</li>
<% end %>
</ul>
</div>
</nav>

<%= yield %>
<script>
$(function () {
$(".alert").fadeOut(5000);
});
</script>

</body>
<footer>
<p>(C)2019. All rights reserved by ABC</p>
</footer>
</html>

app/views/pages/about.html.erb
<div class="schedule-top-wrapper">
  <div class="bg">
  </div>
  <div class="wrapper">

    <div class="submenu">
      <h2>MENU</h2>
      <ul class="submenu-list">
        <li>
          <%= link_to 'SCEDULE', pages_schedule_path %>
        </li>
        <li>
          <%= link_to 'GARRELY', topics_path %>
        </li>
        <li>
          <%= link_to 'ABOUT', '#' %>
        </li>
      </ul>
    </div>

    <div class="main">
      <h1>About</h1>
      <div class="picture">
        

      </div>
    </div>
  </div>
</div>

app/views/pages/help.html.erb
<h1>ヘルプページです</h1>

app/views/pages/index.html.erb
<div class="top-hero-wrapper text-center">
  <div class="container top-hero-container">
    <h1 class="text-white">
      <span>ABC</span>
      English & Baking for kids!</h1>
    <h2 class="text-white">Official Website only for Students.</h2>
    <div class="row">
      <div class="col-md-offset-3 col-md-3">
        <%= link_to 'Sign up', new_user_path, class: 'btn btn-block btn-white' %>
      </div>
      <div class="col-md-3">
        <%= link_to 'Log in', login_path, class: 'btn btn-block btn-white' %>
      </div>
    </div>
  </div>
</div>

app/views/pages/schedule.html.erb
<div class="schedule-top-wrapper">
  <div class="bg"></div>
  <div class="wrapper">

    <div class="submenu">
      <h2>MENU</h2>
      <ul class="submenu-list">
        <li>
          <%= link_to 'SCEDULE', '#' %>
        </li>
        <li>
          <%= link_to 'GARRELY', topics_path %>
        </li>
        <li>
          <%= link_to 'ABOUT', pages_about_path %>
        </li>
      </ul>
    </div>

    <div class="main">
      <h1>Schedule</h1>
      <iframe src="https://calendar.google.com/calendar/embed?src=leotakahashi777%40gmail.com&ctz=Asia%2FTokyo" style="border: 0" width="800" height="600" frameborder="0" scrolling="no"></iframe>
      <!-- <iframe src="https://calendar.google.com/calendar/embed?src=8d0h725ptsaqm8qkigf1lqcg70%40group.calendar.google.com&ctz=Asia%2FTokyo" style="border: 0" width="800" height="600" frameborder="0" scrolling="no"></iframe> -->
      <!-- <iframe src="https://calendar.google.com/calendar/embed?showPrint=0&amp;showTabs=0&amp;showCalendars=0&amp;showTz=0&amp;height=600&amp;wkst=1&amp;bgcolor=%23FFFFFF&amp;src=8d0h725ptsaqm8qkigf1lqcg70%40group.calendar.google.com&amp;color=%23B1440E&amp;src=ja.japanese%23holiday%40group.v.calendar.google.com&amp;color=%238D6F47&amp;ctz=Asia%2FTokyo" style="border-width:0" width="800" height="600" frameborder="0" scrolling="no"></iframe> -->
    </div>
  </div>
</div>

app/views/topics/index.html.erb
<div class="topic-index-wrapper">
  <div class="bg">
  </div>

  <div class="wrapper">

    <div class="submenu">
      <h2>MENU</h2>
      <ul class="submenu-list">
        <li>
          <%= link_to 'SCEDULE', pages_schedule_path %>
        </li>
        <li>
          <%= link_to 'GARRELY', '#' %>
        </li>
        <li>
          <%= link_to 'ABOUT', pages_about_path %>
        </li>
      </ul>
    </div>


      <div class="main">
        <h1>Garrely</h1>
        <% @topics.each do |topic| %>
          <div class="frame">
            <%= image_tag topic.image.url %>
        </div>
    <% end %>
  </div>
</div>

app/views/topics/new.html.erb
<div class="topic-new-wrapper" >
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">Add Picture to Garrely</h1>
        <%= form_for @topic do |f| %>
          <div class="form-group">
            <%= f.label :image %>
            <%= f.file_field :image%>
          </div>

          <div class="form-group">
            <%= f.label :description %>
            <%= f.text_area :description, class: 'form-control' %>
          </div>

          <%= f.submit 'Post', class: 'btn btn-black btn-block' %>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="users-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-4 col-md-4 users-new-container">
        <h1 class="text-center text-white">Sign up</h1>
        <%= form_for @user do |f| %>
        <div class="form-group">
          <%= f.label :name, class: 'text-white' %>
          <%= f.text_field :name, class: 'form-control', :placeholder => "ex. Taro Yamada" %>
        </div>
        <div class="form-group">
          <%= f.label :email, class: 'text-white' %>
          <%= f.text_field :email, class: 'form-control', :placeholder => "ex. hawaii@abc.com" %>
        </div>
        <div class="form-group">
          <%= f.label :password, class: 'text-white' %>
          <%= f.password_field :password, class: 'form-control', :placeholder => "ex. abcd1234" %>
        </div>
        <div class="form-group">
          <%= f.label :password_confirmation, class: 'text-white' %>
          <%= f.password_field :password_confirmation, class: 'form-control', :placeholder => "re-enter your password" %>
        </div>

        <%= f.submit "REGISTER", class: 'btn-block btn-white' %>
      <% end %>
      <%= link_to 'Login>>', login_path, class: 'text-white' %>
    </div>
  </div>
</div>
</div>